name: On push
on: 
  push:
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        go: ['1.12', '1.13', '1.14']

    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Run tests
      run: go test -mod vendor ./... 